name: Get Subtitles

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install youtube-dl
      run: |
        python3 -m pip install youtube-transcript-api

    - name: Download Transcript and Save to File
      run: python get_transcript.py "${{ github.event.inputs.video_id }}"
      working-directory: ${{ github.workspace }}

    - name: Print Transcript
      run: cat transcript.txt
      working-directory: ${{ github.workspace }}

    - name: Save Transcript
      env:
        GH_TOKEN: ${{ secrets.GIST_PAT }}
      run: |
        gist_name="transcript_${{ github.event.inputs.video_id }}.txt"
        gist_description="Transcript for video ${{ github.event.inputs.video_id }}"
        response=$(curl -H "Authorization: token $GH_TOKEN" \
                       -X POST -d "{\"files\": {\"$gist_name\": {\"content\": \"$(<transcript.txt)\"}}, \"description\": \"$gist_description\", \"public\": false}" \
                       https://api.github.com/gists)
      working-directory: ${{ github.workspace }}