name: Get Subtitles

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install youtube-dl
      run: |
        python3 -m pip install -U yt-dlp
        python3 -m pip install youtube-transcript-api

    - name: Download Transcript and Save to File
      run: python download_transcript.py "${{ github.event.inputs.video_id }}"
      working-directory: ${{ github.workspace }}

    - name: Print Transcript
      run: cat transcript.txt
      working-directory: ${{ github.workspace }}
      
    - name: Download Subtitles
      run: |
        yt-dlp --write-auto-subs --skip-download --sub-lang en --sub-format vtt https://www.youtube.com/watch?v=${{ github.event.inputs.video_id }}
        ls

    - uses: FedericoCarboni/setup-ffmpeg@v2

    - name: Convert VTT to SRT
      run: |
        for file in *.vtt; do
          ffmpeg -i "$file" "${file%.vtt}.srt"
        done
        ls

    - name: Print Subtitles
      run: |
        for file in *.srt; do
          echo "Contents of $file:"
          cat "$file"
        done
