name: Get Subtitles

on:
  workflow_dispatch:
    inputs:
      video_id:
        description: 'YouTube Video ID'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install youtube-dl
      run: |
        python3 -m pip install youtube-transcript-api

    - name: Download Transcript and Save to File
      run: python get_transcript.py "${{ github.event.inputs.video_id }}"
      working-directory: ${{ github.workspace }}

    - name: Print Transcript
      run: cat transcript.txt
      working-directory: ${{ github.workspace }}

    - uses: actions/checkout@v3
    - name: Save
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        file_path: ${{ github.workspace }}/transcript.txt